### ISSUE TITLE
PHP_SESSION_TYPE配置成redis共享后在step4就会转到upgrade.php变成空白

### ISSUE THREAD

**Issue by amethystlilj** [quicklyon/zentao-docker#1]

**Comment by zhouyq** [comment]
我们确认一下这个问题，有结果后第一时间反馈

**Comment by zhouyq** [comment]
我们这边确认有问题，已经将问题反馈给禅道开发团队，修复后第一时间反馈。 @amethystlilj

**Comment by zhouyq** [comment]
@amethystlilj  更新镜像到 20220818版本，已经修复该问题。https://github.com/quicklyon/zentao-docker/releases/tag/v20220818
