### ISSUE TITLE
docker-compose运行后一直重启

### ISSUE THREAD

**Issue by manongqiyin** [quicklyon/zentao-docker#10]
我的docker-compose 的配置如下：

version: '3'
services:
 zentao:
   image: easysoft/quickon-zentao:18.5
   restart: always
   ports:
     - '18800:80'
     - '8806:3306'
   volumes:
     - /gdwas/zentao/data:/data
   environment:
     # 数据库密码
     - MYSQL_HOST=******
     - MYSQL_PORT=3306
     - MYSQL_USER=zentao
     - MYSQL_PASSWORD=********
     - MYSQL_DB=zentao
     - LDAP_ENABLED=false
     - SMTP_ENABLED=false
     - LINK_GIT=false
     - LINK_CI=false
     - LINK_SCAN=false
   

用docker-compose 的指令运行后，一直重启。查看docker logs 输出信息如下：
 16:30:09.42 Welcome to the Easysoft ZenTao 18.5 container
 16:30:09.42 Subscribe to project updates by watching https://www.zentao.net
 16:30:09.43 Submit issues and feature requests at https://www.zentao.net/ask.html
 16:30:09.43 
 16:30:09.44 INFO  ==> Prepare persistence directories.
 16:30:09.56 INFO  ==> Render php.ini with environment variables.
 16:30:09.57 INFO  ==> render template php.ini for amd64
 16:30:09.63 INFO  ==> Render apache sites config with envionment variables.
 16:30:09.69 INFO  ==> Check whether the MySQL is available.
 16:30:09.69 INFO  ==> MySQL is ready.
 16:30:09.69 INFO  ==> Check ZenTao 18.5 database.

就卡在数据库这里了

**Comment by ysicing** [comment]
@manongqiyin  quickon-zentao 默认没有mysql，有跑mysql服务么， 可以参考 [docker-compose.yml.example](https://github.com/quicklyon/zentao-docker/blob/master/docker-compose.yml.example#L9)

**Comment by manongqiyin** [comment]
> @manongqiyin quickon-zentao 默认没有mysql，有跑mysql服务么， 可以参考 [docker-compose.yml.example](https://github.com/quicklyon/zentao-docker/blob/master/docker-compose.yml.example#L9)

本地有跑mysql服务的，只是mysql没用docker。MYSQL_HOST和MYSQL_PORT都正确的指向了我本地跑的mysql

**Comment by ysicing** [comment]
看日志报错，应用是检查数据库 [Check ZenTao 18.5 database.](https://github.com/quicklyon/zentao-docker/blob/master/debian/prebuildfs/opt/easysoft/scripts/libmysql.sh#L70C13-L70C13), 具体就是执行mysql

```bash
mysql -u --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute="CREATE DATABASE IF NOT EXISTS  $MYSQL_DB"
```

手动执行一下看看或者开启[debug模式](https://github.com/quicklyon/zentao-docker/blob/master/docker-compose.yml#L64)

**Comment by manongqiyin** [comment]
> 看日志报错，应用是检查数据库 [Check ZenTao 18.5 database.](https://github.com/quicklyon/zentao-docker/blob/master/debian/prebuildfs/opt/easysoft/scripts/libmysql.sh#L70C13-L70C13), 具体就是执行mysql
> 
> ```shell
> mysql -u --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute="CREATE DATABASE IF NOT EXISTS  $MYSQL_DB"
> ```
> 
> 手动执行一下看看或者开启[debug模式](https://github.com/quicklyon/zentao-docker/blob/master/docker-compose.yml#L64)

我开启的debug，在Check ZenTao 18.5 database输出以下信息：
+ debug_execute /usr/bin/mysql --host=*** --port=*** --user=root --password=pass4Zentao '--execute=CREATE DATABASE IF NOT EXISTS zentao;'
+ is_boolean_yes false
+ local -r bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ false
+ /usr/bin/mysql --host=*** --port=*** --user=root --password=pass4Zentao '--execute=CREATE DATABASE IF NOT EXISTS zentao;'
+ return 1
+ exit 1



我的root已经拥有了最高的权限，但是这个password不是我在docker-compose设置的password，这是为啥

**Comment by manongqiyin** [comment]
> 看日志报错，应用是检查数据库 [Check ZenTao 18.5 database.](https://github.com/quicklyon/zentao-docker/blob/master/debian/prebuildfs/opt/easysoft/scripts/libmysql.sh#L70C13-L70C13), 具体就是执行mysql
> 
> ```shell
> mysql -u --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute="CREATE DATABASE IF NOT EXISTS  $MYSQL_DB"
> ```
> 
> 手动执行一下看看或者开启[debug模式](https://github.com/quicklyon/zentao-docker/blob/master/docker-compose.yml#L64)
docker-compose后未能创建数据库， 开了debug后，Check ZenTao 18.5 database的logs信息如下：
+ debug_execute /usr/bin/mysql --host=*** --port=*** --user=zentao --password=*** '--execute=CREATE DATABASE IF NOT EXISTS zentao;'
+ is_boolean_yes false
+ local -r bool=false
+ shopt -s nocasematch
+ [[ false = 1 ]]
+ [[ false =~ ^(yes|true)$ ]]
+ false
+ /usr/bin/mysql --host=*** --port=*** --user=zentao --password=*** '--execute=CREATE DATABASE IF NOT EXISTS zentao;'
+ return 1
+ exit 1


如果手动执行 mysql -u --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute="CREATE DATABASE IF NOT EXISTS  $MYSQL_DB"的话，有一个警告：
mysql: [Warning] Using a password on the command line interface can be insecure.
但是执行该条指令后能创建数据库

**Comment by ysicing** [comment]
还有一个可能就是容器内没法访问你的数据库，你可以先试试将容器网络改成host模式看看，或者用我们提供的mysql镜像启动看看
