### ISSUE TITLE
请问如何升级？

### ISSUE THREAD

**Issue by luo-geng** [quicklyon/zentao-docker#2]
docker版只提供了部署方法，后面升级怎么在docker下，是和官方的操作一样吗？

**Comment by zhouyq** [comment]
升级直接拉最新的镜像就可以了，修改docker-compose.yml 中的镜像tag。

**Comment by luo-geng** [comment]
> 升级直接拉最新的镜像就可以了，修改docker-compose.yml 中的镜像tag。

部署后对已有禅道升级，不是打包。升级的话，按照官方说法，要先覆盖，再访问upgrade.php去升级。因为官方的镜像是在本地连接mysql，所以我用了这个镜像。

我是直接dockerhub拉取[镜像](https://hub.docker.com/r/easysoft/quickon-zentao)部署的，没用docker-compose。

**Comment by zhouyq** [comment]
按照这个仓库的说明文档操作就行，我们对禅道做了适配，更新镜像后，如果数据库中的版本信息与代码版本不一致，会自动触发升级，不需要单独访问upgrade.pho

**Comment by zhouyq** [comment]
参考一下 docker-compose.yml 文件中的环境变量，设置 `IS_CONTAINER`="true" 更新版本后会自动执行升级操作。

**Comment by luo-geng** [comment]
> 参考一下 docker-compose.yml 文件中的环境变量，设置 `IS_CONTAINER`="true" 更新版本后会自动执行升级操作。

好的，感谢 🍵

**Comment by zhouyq** [comment]
客气了，感谢反馈，我们的文档也需要更新。
