### ISSUE TITLE
执行dockerfile报错

### ISSUE THREAD

**Issue by nothingp** [quicklyon/zentao-docker#3]
> [ 3/17] RUN install_packages jq curl wget zip unzip s6 pwgen cron netcat ca-certificates vim-tiny:
#7 0.760 /bin/sh: 1: install_packages: not found

**Comment by ysicing** [comment]
@nothingp 怎么执行的，建议checkout最新tag执行make操作

**Comment by zhouyq** [comment]
通过make help 查看详细的构建命令

**Comment by nothingp** [comment]
> @nothingp 怎么执行的，建议checkout最新tag执行make操作

我就是下载仓库，master分支，然后跑docker build

**Comment by ysicing** [comment]
@nothingp  现在应该是ok了
